import {LabViewer,scales,shade} from './lab-viewer.js';
import {controls,selectComputed} from './catalog-selection.js';
const $=id=>document.getElementById(id),num=(v,n=2)=>v==null?'—':Number(v).toLocaleString('pt-BR',{maximumFractionDigits:n});
let catalog,entry,current,viewer,token=0,visited=[],playing=false;const cache=new Map();
async function json(path){const url='/'+path.replace(/^\//,'');if(!cache.has(url)){const r=await fetch(url);if(!r.ok)throw Error('Arquivo indisponível: '+path);cache.set(url,await r.json());}return cache.get(url);}
function map(data,field){const [lo,hi,unit]=scales[field];return `<svg viewBox="-43 -55 86 112" role="group" aria-label="${field} map">${data.cells.map((c,i)=>`<path data-cell="${i}" tabindex="0" role="button" aria-label="Cell ${c.cell_id}" d="M${c.polygon.map(([x,y])=>x+','+(-y)).join(' L')} Z" fill="${shade(c[field],field)}" stroke="#f4f5ef" stroke-width=".2"/>`).join('')}<text x="-39" y="54" font-size="3">${lo} → ${hi} ${unit}</text></svg>`;}
function inspect(c){$('cell-inspector').innerHTML=`<h2>Cell ${c.cell_id}</h2><dl><dt>Demand</dt><dd>${num(c.demand)}%</dd><dt>λ1 / λ2</dt><dd>${num(c.lambda1)} / ${num(c.lambda2)}</dd><dt>Reference width</dt><dd>1 mm · A</dd><dt>Current mean width</dt><dd>${num(c.width)} mm</dd><dt>Reference height</dt><dd>1 mm · A</dd><dt>Current mean height</dt><dd>${num(c.height)} mm</dd></dl><strong>${c.mechanism}</strong><p>${c.mechanism_reason||''}</p><p class="quiet">Cell means; actual ligament heights are quantized to 0.1 mm. ${c.fit_warning?'Local affine fit is weak.':''}</p>`;}
function setControls(){const p=entry.parameters;for(const [id,key]of Object.entries(controls)){if(id==='equal')$(id).checked=p[key];else $(id).value=p[key];}
 for(const [id,key,suffix]of [['pitch-value','pitch_mm',' mm'],['width-value','base_width_mm',' mm'],['height-value','base_height_mm',' mm'],['wg-value','width_response','%'],['hg-value','height_response','%'],['budget-value','material_budget_pct','%']])$(id).textContent=num(p[key]*(key.endsWith('response')?100:1))+suffix;
 for(const id of ['adaptation','response'])for(const option of $(id).options)option.disabled=!catalog.designs.some(e=>e.part===entry.part&&e.parameters.topology===p.topology&&e.parameters[controls[id]]===option.value);
 $('configuration').innerHTML=catalog.designs.filter(e=>e.part===entry.part).map(e=>`<option value="${e.id}">${e.name}</option>`).join('');$('configuration').value=entry.id;
 $('part').value=entry.part;$('budget').disabled=p.equal_material;$('orientation').closest('label').hidden=p.topology!=='diamond';
}
function view(){if(!current)return;viewer.field=$('field').value;viewer.formed=$('state').value==='formed';viewer.exaggeration=+$('exaggeration').value;viewer.ghost=$('ghost').checked;
 if(viewer.field==='difference'){viewer.mode='difference';viewer.formed=false;$('state').value='flat';}
 viewer.update();$('visual-note').textContent=viewer.formed?'Formed solver network: constrained target surface, not a deformed solid STL.':viewer.exaggeration>1?`Height visually exaggerated ${viewer.exaggeration}×. STL dimensions remain physical.`:'Actual solid dimensions. Height quantum: 0.1 mm.';
 const s=scales[viewer.field];$('legend').textContent=viewer.mode==='difference'?'Green: added material · red: removed material':s?`${s[0]} → ${s[1]} ${s[2]} · saturated outside range`:'Mechanism: design heuristic';
 document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===viewer.mode)));
}
function curve(){const edges=current.edges.filter((_,i)=>i%Math.max(1,Math.floor(current.edges.length/70))===0);const points=field=>edges.map(e=>`<circle cx="${15+Math.min(1,e.demand/70)*205}" cy="${105-(e[field]-.7)/1.3*85}" r="1.8" fill="${field==='width'?'#3d774d':'#b58a49'}"/>`).join('');$('response-curve').innerHTML=`<svg viewBox="0 0 240 145"><path d="M15,10 V110 H230" fill="none" stroke="#adbca2"/>${points('width')}${points('height')}<text x="15" y="128" font-size="9">0 → 70% solved demand</text><text x="15" y="142" font-size="9" fill="#3d774d">width</text><text x="65" y="142" font-size="9" fill="#b58a49">height · mm</text></svg>`;}
async function load(){const t=++token;setControls();$('computed-status').textContent='Loading computed design…';$('metrics').replaceChildren();try{
 const baseline=catalog.designs.find(e=>e.part===entry.part&&e.id==='A_uniform');const [d,a,tool]=await Promise.all([json(entry.data),json(baseline.data),json('data/parametric/tool_'+entry.part+'.json')]);if(t!==token)return;current=d;viewer.setData(d,a,tool);$('design-name').textContent=entry.name;$('computed-status').textContent='Computed design · '+(entry.solver_converged?'solver converged':'solver NOT converged');
 const m=entry.metrics;$('metrics').innerHTML=[['P95 demand',num(m.p95)+'%'],['Maximum demand',num(m.maximum)+'%'],['Critical ligaments >30%',m.critical_edges],['Material Δ · lattice vs A',(m.material_delta_pct>=0?'+':'')+num(m.material_delta_pct)+'%'],['Open area',num(m.open_area)+'%'],['Minimum feature',num(m.minimum_feature_mm)+' mm']].map(([label,value])=>`<div><dt>${label}</dt><dd>${value}</dd></div>`).join('');
 for(const [id,f]of [['deformation-map','demand'],['width-map','width'],['height-map','height'],['material-map','area']])$(id).innerHTML=map(d,f);inspect(d.cells[0]);curve();view();
 $('stl-download').href='/'+entry.stl;$('stl-download').textContent=(entry.part==='hab2'?'HAB-2':'Sub-Merged')+' STL ↓';const other=catalog.designs.find(e=>e.part!==entry.part&&e.id===entry.id);$('companion-stl').href='/'+other.stl;$('companion-stl').textContent=(other.part==='hab2'?'HAB-2':'Sub-Merged')+' · same configuration STL ↓';$('part-pack').href='/downloads/parametric/'+entry.part+'/LAMPFORM_PARAMETRIC_TEST_V2.zip';$('download-status').textContent=`Computed · STL ${entry.validation.valid?'valid':'INVALID'} · Solver ${entry.solver_converged?'converged':'NOT converged'}`;
 $('details').textContent=JSON.stringify({parameters:entry.parameters,actual_volume_mm3:m.material_volume_mm3,lattice_volume_mm3:m.lattice_volume_mm3,levels_mm:entry.validation.levels_mm,solver_degrees_of_freedom:'XY translations; Z constrained by real target surface',in_plane:'relative axial and angular penalties use width and height',out_of_plane:'section inertia stored, no independent out-of-plane bending DOFs'},null,2);
 if(!visited.some(h=>h.id===entry.id&&h.part===entry.part))visited.unshift(entry);visited=visited.slice(0,12);historyUI();window.history.replaceState(null,'','/design/?'+new URLSearchParams({part:entry.part,design:entry.id}));
 }catch(e){$('computed-status').textContent=e.message;$('computed-status').className='error';}}
function historyUI(){const checks=[...document.querySelectorAll('#history input:checked')].map(e=>e.value);$('history').innerHTML=visited.map(e=>`<label><input type="checkbox" value="${e.part}/${e.id}" ${checks.includes(e.part+'/'+e.id)?'checked':''}>${e.part} · ${e.name}</label>`).join('');$('history').onchange=e=>{const selected=[...document.querySelectorAll('#history input:checked')];if(selected.length>3){e.target.checked=false;$('snap-note').textContent='Compare até três designs por vez.';return;}const designs=selected.map(x=>visited.find(h=>h.part+'/'+h.id===x.value));$('history-comparison').innerHTML='<tr><th>Design</th><th>P95</th><th>Volume lattice</th><th>Open area</th><th>Maximum height</th></tr>'+designs.map(d=>`<tr><td>${d.part} · ${d.name}</td><td>${num(d.metrics.p95)}%</td><td>${num(d.metrics.lattice_volume_mm3)} mm³</td><td>${num(d.metrics.open_area)}%</td><td>${num(d.metrics.maximum_height_mm)} mm</td></tr>`).join('');};}
async function main(){catalog=await json('data/parametric/catalog.json');const query=new URLSearchParams(location.search);entry=catalog.designs.find(e=>e.id===query.get('design')&&e.part===query.get('part'))||catalog.designs[0];viewer=new LabViewer($('viewer'),inspect);
 for(const [id,key]of Object.entries(controls))$(id).onchange=()=>{playing=false;const value=id==='equal'?$(id).checked:['topology','adaptation','response'].includes(id)?$(id).value:+$(id).value;const prior=entry;entry=selectComputed(catalog.designs,entry,key,value);$('snap-note').textContent=entry===prior?'No other computed configuration matches this choice.':'Snapped to computed configuration: '+entry.name+'. All controls show its exact parameters.'+(entry.parameters.equal_material?' Equal volume is the common feasible target across three topologies, about +38% vs A.':' The material cap can make different response gains produce the same geometry.');load();};
 $('part').onchange=()=>{playing=false;entry=catalog.designs.find(e=>e.part===$('part').value&&e.id===entry.id)||catalog.designs.find(e=>e.part===$('part').value);load();};$('configuration').onchange=()=>{playing=false;entry=catalog.designs.find(e=>e.part===entry.part&&e.id===$('configuration').value);$('snap-note').textContent='Exact computed configuration selected.';load();};$('run').onclick=load;$('export-config').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({version:'0.8.0',...entry.parameters,part:entry.part},null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='lampform-design-configuration.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);};
 for(const id of ['state','field','exaggeration','ghost'])$(id).onchange=()=>{if((id==='field'&&$('field').value!=='difference')||(id==='state'&&$('state').value==='formed')){if(viewer.mode==='difference')viewer.mode='current';if($('state').value==='formed'&&$('field').value==='difference')$('field').value='demand';}view();};document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>viewer.preset(b.dataset.camera));document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{viewer.mode=b.dataset.mode;if(viewer.mode==='difference')$('state').value='flat';else if($('field').value==='difference')$('field').value='demand';view();});
 for(const id of ['deformation-map','width-map','height-map','material-map']){const click=e=>{const p=e.target.closest('[data-cell]');if(p)inspect(current.cells[+p.dataset.cell]);};$(id).onclick=click;$(id).onkeydown=e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();click(e);}};}
 $('video').onclick=async()=>{if(playing){playing=false;return;}playing=true;$('video').textContent='Stop sequence';for(const [id,field,label]of [['A_uniform','width','Uniform lattice'],['A_uniform','demand','Calculated deformation field'],['B_width','width','Adaptive width'],['C_height','height','Adaptive height'],['D_both','height','Final computed STL']]){if(!playing)break;entry=catalog.designs.find(e=>e.id===id&&e.part===$('part').value);$('field').value=field;$('state').value='flat';viewer.mode='current';$('video-note').textContent=label+' · transition between computed designs';await load();if(!matchMedia('(prefers-reduced-motion: reduce)').matches)$('viewer').animate([{opacity:.15},{opacity:1}],{duration:900});await new Promise(r=>setTimeout(r,2400));}playing=false;$('video').textContent='Play computed design sequence';};await load();}
main().catch(e=>$('computed-status').textContent=e.message);
