import {CompareViewer} from './compare-viewer.js';
import {json} from './research-data.js';
import {hypotheses,partName,partSlug,partId,stlPath,imagePath,baselineId,comparison,exactAlternative} from './experiment-library.js';
import {downloadPair} from './test-download.js';
const $=id=>document.getElementById(id),n=(v,d=2)=>Number(v).toLocaleString('pt-BR',{maximumFractionDigits:d});
let cat,part,entry,reference,question='material',stage='choose-part',viewer,ticket=0;
const panels=['choose-part','choose-question','choose-hypothesis','choose-topology','compare','result','tune'];
const title=e=>hypotheses.find(h=>h.id===e.id)?.name||e.name.replace(/^[A-D] · /,'');
function card(p,id,name,description,sample=''){return `<button class="choice" data-design="${id}"><img src="${imagePath(p,id)}" alt="Geometria real: ${name}" loading="lazy"><small>${sample}</small><h3>${name}</h3><p>${description}</p></button>`;}
function show(next){stage=next;window.scrollTo({top:0,behavior:'instant'});for(const id of panels)$(id).hidden=id!==next;$('back').hidden=next==='choose-part';$('context').textContent=part?partName(part)+' · '+(question==='topology'?'TOPOLOGY':'MATERIAL'):'DESIGN · EXPLORE';$('error').textContent='';const q=new URLSearchParams();if(part)q.set('part',partSlug(part));if(entry)q.set('design',entry.id);q.set('stage',next);history.replaceState(null,'','/design/?'+q);}
function choosePart(p){part=p;entry=null;question='material';$('go-test').href='/test/?part='+partSlug(part);show('choose-question');}
function choices(mode){question=mode;if(mode==='material'){$('hypotheses').innerHTML=hypotheses.map(h=>card(part,h.id,h.name,h.description,'Sample '+h.sample)).join('');show('choose-hypothesis');}else{$('topologies').innerHTML=['honeycomb','triangle','diamond'].map(k=>card(part,k+'_equal',k==='honeycomb'?'Honeycomb':k==='triangle'?'Triangle':'Diamond',k==='honeycomb'?'Referência de volume equivalente.':'Mesmo volume. Outra geometria de célula.')).join('');show('choose-topology');}}
async function select(id){entry=cat.designs.find(e=>e.part===part&&e.id===id);reference=cat.designs.find(e=>e.part===part&&e.id===baselineId(entry));question=entry.parameters.equal_material?'topology':'material';const t=++ticket;show('compare');document.body.classList.add('loading');$('computed-label').textContent='Carregando design calculado…';$('see-result').disabled=true;$('compare-title').textContent=title(entry);$('before-label').textContent=question==='topology'?'HONEYCOMB · MESMO VOLUME':'ORIGINAL · CONTROLE';$('reference-note').textContent=question==='topology'?'Comparação com Honeycomb de volume equivalente, não com o controle de menor volume.':'Original = controle uniforme gerado para o experimento. O arquivo original fornecido está preservado em Advanced.';
 try{const [a,raw,tool]=await Promise.all([json(reference.data),json(entry.data),json('data/parametric/tool_'+part+'.json')]);const d=question==='topology'?{...raw,...await json('media/comparisons/'+part+'-'+entry.id+'.json')}:raw;if(t!==ticket)return;if(!viewer)viewer=new CompareViewer($('comparison-viewer'));viewer.setData(a,d,tool);$('reveal').value='50';viewer.reveal(50);view('geometry');$('computed-label').textContent='Design calculado · STL verificado';$('see-result').disabled=false;document.body.classList.remove('loading');}catch(e){if(t===ticket){$('error').textContent=e.message;document.body.classList.remove('loading');}}}
function view(mode){if(!viewer)return;$('view-note').textContent=viewer.show(mode);$('reveal-control').hidden=mode==='difference';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===mode)));}
function results(){if(!entry)return;const r=comparison(reference,entry);$('result-title').textContent=title(entry);$('result-metrics').innerHTML=r.metrics.map(m=>`<div class="metric"><h3>${m.label}</h3><span class="value">${n(m.before)} → ${n(m.after)}${m.unit}</span><p>${m.question}</p><span class="direction ${m.direction}">${{better:'↓ BETTER',worse:'↑ WORSE',similar:'≈ SIMILAR'}[m.direction]}</span></div>`).join('')+`<div class="metric"><h3>Material</h3><span class="value">${r.materialDelta>=0?'+':''}${n(r.materialDelta)}%</span><p>Volume de malha relativo à referência; aro excluído.</p><span class="direction similar">${Math.abs(r.materialDelta)<.1?'≈ MESMO VOLUME':r.materialDelta>0?'↑ MAIS MATERIAL':'↓ MENOS MATERIAL'}</span></div>`;$('test-status').textContent=r.status;$('result-explanation').textContent=r.explanation;$('download-stl').href=stlPath(entry);$('download-pair').hidden=entry.id===reference.id;$('fine-tune').hidden=question==='topology';show('result');}
function tune(){show('tune');$('tune-options').innerHTML=[['base_width_mm','Width · mm',[.8,1,1.2]],['base_height_mm','Height · mm',[.8,1,1.2]],['material_budget_pct','Material budget · %',[0,10,20]]].map(([key,label,values])=>`<fieldset><legend>${label}</legend>${values.map(value=>{const match=exactAlternative(cat.designs,entry,key,value);return `<button data-tune="${key}" data-value="${value}" ${match?'':'disabled'} aria-pressed="${entry.parameters[key]===value}">${value}</button>`;}).join('')}</fieldset>`).join('');$('tune-note').textContent='Design atual: '+title(entry)+'. Valores indisponíveis exigem outro cálculo e permanecem desabilitados.';}
$('back').onclick=()=>{ticket++;document.body.classList.remove('loading');if(stage==='choose-question'){entry=null;part=null;show('choose-part');}else if(['choose-hypothesis','choose-topology'].includes(stage))show('choose-question');else if(stage==='compare')choices(question);else if(stage==='result')show('compare');else if(stage==='tune')results();};
document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>choices(b.dataset.question));for(const id of ['hypotheses','topologies'])$(id).onclick=e=>{const b=e.target.closest('[data-design]');if(b)select(b.dataset.design);};document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$('reveal').oninput=e=>viewer?.reveal(e.target.value);$('see-result').onclick=results;$('fine-tune').onclick=tune;
$('tune-options').onclick=e=>{const b=e.target.closest('[data-tune]');if(!b||b.disabled)return;const match=exactAlternative(cat.designs,entry,b.dataset.tune,+b.dataset.value);if(match)select(match.id);};
$('download-pair').onclick=async()=>{const button=$('download-pair');button.disabled=true;button.textContent='Preparando o par de teste…';try{await downloadPair(reference,entry);}catch(e){$('error').textContent=e.message;}finally{button.disabled=false;button.textContent='Download test pair · Original + Candidate ↓';}};
async function main(){cat=await json('data/parametric/catalog.json');$('parts').innerHTML=['hab2','submerged'].map(p=>`<button class="choice" data-part="${p}"><img src="${imagePath(p,'A_uniform')}" alt="Geometria real ${partName(p)}"><small>ESCOLHER PEÇA</small><h3>${partName(p)}</h3><p>${p==='hab2'?'Referência com o Molde da Peça 1.':'Referência com o Molde da Peça 2.'}</p></button>`).join('');$('parts').onclick=e=>{const b=e.target.closest('[data-part]');if(b)choosePart(b.dataset.part);};const q=new URLSearchParams(location.search);part=['hab2','submerged'].includes(partId(q.get('part')))?partId(q.get('part')):null;const id=q.get('design');if(part&&cat.designs.some(e=>e.part===part&&e.id===id)){await select(id);if(q.get('stage')==='result')results();}else if(part)choosePart(part);else show('choose-part');}
main().catch(e=>$('error').textContent=e.message);

const handle=document.querySelector('.reveal-line');handle.onpointerdown=e=>{if(!viewer||viewer.mode==='difference')return;e.preventDefault();handle.setPointerCapture(e.pointerId);const move=event=>{const box=$('comparison-viewer').getBoundingClientRect(),value=Math.max(0,Math.min(100,(event.clientX-box.left)/box.width*100));$('reveal').value=value;viewer.reveal(value);};handle.onpointermove=move;handle.onpointerup=()=>{handle.onpointermove=null;handle.onpointerup=null;};move(e);};
