import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
export const scales={demand:[0,60,'%'],width:[.8,1.6,'mm'],height:[.8,2,'mm'],area:[.64,3.2,'mm²'],lambda1:[1,1.8,'×']};
export function shade(value,field){if(!Number.isFinite(value))return '#b2bda8';const [a,b]=scales[field]||scales.demand,t=Math.max(0,Math.min(1,(value-a)/(b-a)));return new THREE.Color().setHSL(.30*(1-t),.48,.40+.15*Math.sin(t*Math.PI)).getStyle();}
const categories={'MATERIAL RESERVE':'#bb7d47','DIRECTIONAL COMPLIANCE':'#427f90','BOUNDARY FEED':'#8d789e','AREA EXPANSION':'#af6674','MIXED':'#858461','LOW DEMAND':'#afc4a6'};
export class LabViewer{
 constructor(element,onCell=()=>{}){this.el=element;this.onCell=onCell;this.objects=[];this.mode='current';this.field='demand';this.exaggeration=1;this.formed=false;
  this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.setClearColor('#edf0e7',0);element.append(this.renderer.domElement);
  this.scene=new THREE.Scene();this.scene.add(new THREE.HemisphereLight(0xffffff,0x7a846f,3));const light=new THREE.DirectionalLight(0xffffff,3);light.position.set(-60,-70,140);this.scene.add(light);
  this.camera=new THREE.PerspectiveCamera(31,1,.1,1500);this.camera.up.set(0,0,1);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.minDistance=65;this.controls.maxDistance=450;this.controls.addEventListener('change',()=>this.render());
  this.ray=new THREE.Raycaster();this.renderer.domElement.addEventListener('pointerdown',e=>{this.down=[e.clientX,e.clientY]});this.renderer.domElement.addEventListener('pointerup',e=>{if(!this.down||Math.hypot(e.clientX-this.down[0],e.clientY-this.down[1])>5)return;const r=element.getBoundingClientRect();this.ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),this.camera);const hit=this.ray.intersectObjects(this.objects).find(h=>h.object.userData.inspect);if(hit&&this.active?.cells?.length){const c=this.active.cells.reduce((a,b)=>Math.hypot(a.center[0]-hit.point.x,a.center[1]-hit.point.y)<Math.hypot(b.center[0]-hit.point.x,b.center[1]-hit.point.y)?a:b);this.onCell(c,this.active);}});
  new ResizeObserver(()=>{const r=element.getBoundingClientRect();if(!r.width||!r.height)return;this.renderer.setSize(r.width,r.height);this.camera.aspect=r.width/r.height;this.camera.updateProjectionMatrix();this.render();}).observe(element);this.preset('iso');
 }
 render(){this.renderer.render(this.scene,this.camera)}
 preset(name){const views={iso:[110,-145,125],top:[0,-.01,225],side:[155,-75,24]};this.camera.position.fromArray(views[name]||views.iso);this.controls.target.set(0,0,this.formed?20:2);this.controls.update();this.render();}
 mesh(source,color,opacity=1){if(!source?.positions?.length)return null;const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(source.positions,3));g.setIndex(source.indices);g.computeVertexNormals();const m=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color,roughness:.77,transparent:opacity<1,opacity,side:THREE.DoubleSide,depthWrite:opacity===1}));this.objects.push(m);this.scene.add(m);return m;}
 clear(){for(const o of this.objects){this.scene.remove(o);o.geometry.dispose();o.material.dispose();}this.objects=[];}
 setData(data,reference,tool){this.data=data;this.reference=reference||data;this.tool=tool;this.update();}
 edgeValue(edge,data){if(this.field==='mechanism'||this.field==='lambda1'){const p=edge.flat,c=data.cells.reduce((a,b)=>Math.hypot(a.center[0]-(p[0]+p[3])/2,a.center[1]-(p[1]+p[4])/2)<Math.hypot(b.center[0]-(p[0]+p[3])/2,b.center[1]-(p[1]+p[4])/2)?a:b);return this.field==='mechanism'?c.mechanism:c.lambda1;}return edge[this.field];}
 update(){if(!this.data)return;this.clear();const d=this.mode==='original'?this.reference:this.data;this.active=d;
  if(this.mode==='difference'&&!this.formed){this.mesh(this.data.added,'#357854');this.mesh(this.data.removed,'#b45559',.75);if(this.ghost)this.mesh(this.reference.lamp,'#98a68b',.1);this.render();return;}
  const values=(d.edges||[]).map(e=>this.edgeValue(e,d)),colors=values.map(v=>new THREE.Color(this.field==='mechanism'?categories[v]||'#b4bea9':this.field==='neutral'?'#a7b79b':shade(v,this.field)));
  if(this.formed){if(this.tool)this.mesh(this.tool,'#a7b59d',.12);const geometry=new THREE.CylinderGeometry(.24,.24,1,5),material=new THREE.MeshBasicMaterial({depthTest:false}),net=new THREE.InstancedMesh(geometry,material,d.edges.length),obj=new THREE.Object3D(),up=new THREE.Vector3(0,1,0);d.edges.forEach((e,i)=>{const coords=e.stages[this.step??4],a=new THREE.Vector3(...coords.slice(0,3)),b=new THREE.Vector3(...coords.slice(3)),v=b.clone().sub(a);obj.position.copy(a).add(b).multiplyScalar(.5);obj.quaternion.setFromUnitVectors(up,v.clone().normalize());obj.scale.set(1,v.length(),1);obj.updateMatrix();net.setMatrixAt(i,obj.matrix);net.setColorAt(i,colors[i]);});net.userData.inspect=true;net.instanceMatrix.needsUpdate=true;net.computeBoundingSphere();this.scene.add(net);this.objects.push(net);
  }else{if(this.ghost&&this.mode!=='original')this.mesh(this.reference.lamp,'#7c9272',.15);const mesh=this.mesh(d.lamp,'white');mesh.userData.inspect=true;mesh.material.vertexColors=true;const pos=mesh.geometry.attributes.position,cs=new Float32Array(pos.count*3);for(let i=0;i<pos.count;i++){const e=pos.getZ(i)>2.01?-1:(d.vertex_edges?.[i]??-1);(e<0||!colors[e]?new THREE.Color('#b6c1ad'):colors[e]).toArray(cs,i*3);if(e>=0&&pos.getZ(i)<3.5)pos.setZ(i,pos.getZ(i)*this.exaggeration);}pos.needsUpdate=true;mesh.geometry.setAttribute('color',new THREE.BufferAttribute(cs,3));mesh.geometry.computeVertexNormals();}
  this.render();
 }
}
