import {LabViewer} from './lab-viewer.js';
const $=id=>document.getElementById(id),cache=new Map();let catalog,legacy,chapter=0,ticket=0,viewer,part='hab2',topology='honeycomb',candidate='A_uniform';
const texts=[
 ['A PEÇA','Uma malha plana.<br>Outra forma possível.','Uma pesquisa sobre transformar uma estrutura impressa em 3D em uma peça curva, preservando o desenho da sua malha.'],
 ['O PROBLEMA','A forma muda.<br>A malha precisa acompanhar.','Ao assumir uma curvatura, as células não se deformam por igual. O desafio é descobrir onde a geometria pede mais movimento — e onde a estrutura pode resistir a ele.'],
 ['MODELO DIGITAL','Dar à geometria<br>uma maneira de responder.','O modelo parte dos arquivos reais da peça e da ferramenta. Uma rede de ligamentos representa a estrutura; largura e altura entram nas suas propriedades de seção.'],
 ['DEFORMAÇÃO','Uma peça.<br>Muitas demandas locais.','O solver calcula como a rede se redistribui sobre a superfície da ferramenta. As cores mostram a demanda geométrica de cada ligamento, não uma previsão calibrada de ruptura.'],
 ['REDESENHO','Distribuir material<br>onde faz sentido testar.','Variar a largura ou a altura cria respostas diferentes. Explore designs calculados e compare a geometria que será realmente exportada.'],
 ['PREVISÃO','Mais material<br>não garante menos deformação.','Quatro experimentos separam os efeitos: A uniforme, B largura, C altura e D ambos. O resultado é uma hipótese mensurável para o próximo ensaio.'],
 ['TESTE FÍSICO','A próxima resposta<br>vem da peça impressa.','Imprimir, termoformar e medir fecha o ciclo. O pacote reúne quatro designs por peça, seus mapas e previsões para registrar o que realmente aconteceu.']
];
async function json(p){if(!cache.has(p)){const r=await fetch('/'+p.replace(/^\//,''));if(!r.ok)throw Error('Não foi possível carregar '+p);cache.set(p,await r.json());}return cache.get(p);}
async function data(id){return json(catalog.designs.find(e=>e.part===part&&e.id===id).data);}
const format=v=>Number(v).toLocaleString('pt-BR',{maximumFractionDigits:1});
async function show(){const t=++ticket;document.body.classList.add('loading');$('story-error').textContent='';const [label,title,copy]=texts[chapter];$('chapter-label').textContent=`0${chapter+1} / 07 · ${label}`;$('chapter-title').innerHTML=title;$('chapter-copy').textContent=copy;$('chapter-extra').replaceChildren();$('previous').disabled=chapter===0;$('next').disabled=chapter===6;document.querySelectorAll('[data-chapter]').forEach(b=>b.setAttribute('aria-current',+b.dataset.chapter===chapter?'step':'false'));
 try{const [a,tool]=await Promise.all([data('A_uniform'),json('data/parametric/tool_'+part+'.json')]);if(t!==ticket)return;let d=a;viewer.formed=false;viewer.mode='current';viewer.field='neutral';viewer.exaggeration=1;viewer.ghost=false;viewer.step=4;
 $('model-caption').textContent=(part==='hab2'?'HAB-2':'Sub-Merged')+' · A uniforme';$('model-note').textContent='Arraste para girar · scroll para aproximar';
 if(chapter===0){const source=legacy.designs.find(e=>e.id==='original')[part];const original=await json(source.data);if(t!==ticket)return;d={lamp:original.lamp,edges:[],cells:[],vertex_edges:[]};$('model-caption').textContent=(part==='hab2'?'HAB-2':'Sub-Merged')+' · arquivo original';}
 if(chapter===1||chapter===3){viewer.formed=true;viewer.field='demand';$('model-note').textContent='Demanda 0 → 60% · rede calculada sobre a superfície real';}
 if(chapter===2){viewer.formed=true;viewer.field='neutral';$('chapter-extra').innerHTML='<p>A = w·h &nbsp; · &nbsp; I no plano = h·w³/12</p><p>XY é resolvido; Z acompanha a superfície. Flexão completa fora do plano e aquecimento local ainda não são calibrados.</p>';$('model-note').textContent='Ferramenta real em transparência · rede calculada';}
 if(chapter===4){const id=topology==='honeycomb'?candidate:topology+'_uniform';d=await data(id);if(t!==ticket)return;viewer.field=candidate==='C_height'||candidate==='D_both'?'height':'width';$('model-caption').textContent=d.parameters.name+' · sólido real';$('model-note').textContent='Altura real, em passos de 0,1 mm. Amplie o relevo no Design Lab.';$('chapter-extra').innerHTML=`<div class="mini-controls"><label>Topologia<select id="mini-topology"><option value="honeycomb">Honeycomb</option><option value="triangle">Triangular</option><option value="diamond">Diamond</option></select></label><label>Adaptação<select id="mini-adaptation"><option value="A_uniform">A · Uniforme</option><option value="B_width">B · Largura</option><option value="C_height">C · Altura</option><option value="D_both">D · Ambas</option></select></label></div><p class="mini-note">Catálogo calculado. DOE adaptativo disponível em Honeycomb; três topologias comparáveis por volume no laboratório.</p>`;$('mini-topology').value=topology;$('mini-adaptation').value=topology==='honeycomb'?candidate:'A_uniform';$('mini-adaptation').disabled=topology!=='honeycomb';$('mini-topology').onchange=e=>{topology=e.target.value;show();};$('mini-adaptation').onchange=e=>{candidate=e.target.value;show();};}
 if(chapter===5){d=await data('D_both');if(t!==ticket)return;viewer.field='demand';viewer.formed=true;const rows=catalog.designs.filter(e=>e.part===part&&catalog.doe.includes(e.id));$('chapter-extra').innerHTML=rows.map(e=>`<div class="result-line"><span>${e.name}</span><strong>P95 ${format(e.metrics.p95)}%</strong></div>`).join('')+'<p class="mini-note">B e C: cerca de +10% de volume de malha vs A. Mesma referência gerada; resultados deste modelo não são diretamente comparáveis aos da v0.6.</p>';$('model-caption').textContent='D · Largura + altura · previsão';$('model-note').textContent='P95: demanda abaixo da qual estão 95% dos ligamentos';}
 if(chapter===6){d=await data('C_height');if(t!==ticket)return;viewer.field='height';$('model-caption').textContent='C · Altura variável · STL pronto para ensaio';$('chapter-extra').innerHTML='<a class="download" href="/downloads/LAMPFORM_PARAMETRIC_TEST_V2.zip" download>Baixar pacote de teste V2 · HAB-2 + Sub-Merged ↓</a><p>Camadas de 0,1 mm · parâmetros e previsões incluídos.<br>Nenhum resultado físico registrado ainda.</p><p class="thermal">A altura altera a rigidez e a resposta térmica. O aquecimento local ainda não foi calibrado.</p>';$('model-note').textContent='Mapa de altura 0,8 → 2 mm · dimensões reais';}
 viewer.setData(d,a,tool);viewer.preset(chapter===6?'side':chapter===3?'top':'iso');document.body.classList.remove('loading');if(!matchMedia('(prefers-reduced-motion: reduce)').matches)$('story-viewer').animate([{opacity:.15},{opacity:1}],{duration:650});history.replaceState(null,'','#chapter-'+(chapter+1));
 }catch(e){$('story-error').textContent=e.message;document.body.classList.remove('loading');}}
catalog=await json('data/parametric/catalog.json');legacy=await json('data/physical/results.json');viewer=new LabViewer($('story-viewer'));const initial=Number(location.hash.replace('#chapter-',''))-1;if(initial>=0&&initial<7)chapter=initial;document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{chapter=+b.dataset.chapter;show();});document.querySelectorAll('[data-camera]').forEach(b=>b.onclick=()=>viewer.preset(b.dataset.camera));$('story-part').onchange=e=>{part=e.target.value;show();};$('previous').onclick=()=>{chapter=Math.max(0,chapter-1);show();};$('next').onclick=()=>{chapter=Math.min(6,chapter+1);show();};document.addEventListener('keydown',e=>{if(['SELECT','INPUT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){chapter=Math.max(0,Math.min(6,chapter+(e.key==='ArrowRight'?1:-1)));show();}});await show();
