import {LabViewer} from './lab-viewer.js';
import {json} from './research-data.js';
import {partName,partSlug,hypotheses} from './experiment-library.js';
const $=id=>document.getElementById(id);let catalog,legacy,viewer,chapter=0,ticket=0,part='hab2',candidate='B_width';
const texts=[['A PEÇA','LampForm.','Impresso plano. Feito para ganhar forma.'],['O PROBLEMA','A malha precisa<br>acompanhar a forma.','A peça plana precisa assumir esta superfície. Algumas regiões pedem muito mais deformação que outras.'],['O MODELO','Onde a peça<br>precisa se deformar?','Transformamos o STL real em uma rede. O modelo calcula a demanda de cada ligamento — e as cores mostram onde ela se concentra.'],['O REDESENHO','Mudar uma variável.<br>Ver o que acontece.','Largura, altura e topologia abrem hipóteses diferentes. Aqui, compare os desenhos que já foram calculados.'],['O EXPERIMENTO','Agora, a peça<br>precisa responder.','As previsões ainda precisam ser testadas. Imprima, aqueça, forme e compare o que aconteceu de verdade.']];
const data=id=>json(catalog.designs.find(e=>e.part===part&&e.id===id).data);
async function show(){const t=++ticket;document.body.classList.add('loading');$('story-error').textContent='';const [label,title,copy]=texts[chapter];$('chapter-label').textContent=`0${chapter+1} / 05 · ${label}`;$('chapter-title').innerHTML=title;$('chapter-copy').textContent=copy;$('chapter-extra').replaceChildren();$('previous').disabled=chapter===0;$('next').disabled=chapter===4;document.querySelectorAll('[data-chapter]').forEach(b=>b.setAttribute('aria-current',+b.dataset.chapter===chapter?'step':'false'));
 try{const [a,tool]=await Promise.all([data('A_uniform'),json('data/parametric/tool_'+part+'.json')]);if(t!==ticket)return;let d=a;viewer.formed=false;viewer.mode='current';viewer.field='neutral';viewer.exaggeration=1;viewer.ghost=false;$('model-caption').textContent=partName(part);$('model-note').textContent='Arraste para girar · aproxime para ver a malha';const cta=document.querySelector('.explore');cta.href='/design/?part='+partSlug(part);cta.innerHTML='Explorar um experimento <span>↗</span>';
 if(chapter===0){const source=await json(legacy.designs.find(e=>e.id==='original')[part].data);if(t!==ticket)return;d={lamp:source.lamp,edges:[],cells:[],vertex_edges:[]};$('model-caption').textContent=partName(part)+' · impressa plana';}
 if(chapter===1||chapter===2){viewer.formed=true;viewer.field=chapter===2?'demand':'neutral';$('model-caption').textContent=partName(part)+' · Molde da '+partName(part);$('model-note').textContent=chapter===2?'Demanda geométrica 0 → 60%. Não é previsão calibrada de ruptura.':'Rede calculada sobre a superfície do molde. A peça real ainda será testada.';}
 if(chapter===3){d=await data(candidate);if(t!==ticket)return;viewer.field='neutral';viewer.exaggeration=['C_height','D_both'].includes(candidate)?3:1;$('model-caption').textContent=partName(part)+' · '+hypotheses.find(h=>h.id===candidate).name;$('model-note').textContent=viewer.exaggeration===3?'Relevo ampliado 3× para leitura. O arquivo mantém a altura real.':'Sólido real calculado. Compare a referência e a hipótese.';$('chapter-extra').innerHTML=`<label class="story-choice">Hipótese<select id="mini-hypothesis">${hypotheses.map(h=>`<option value="${h.id}">${h.name}</option>`).join('')}</select></label>`;$('mini-hypothesis').value=candidate;$('mini-hypothesis').onchange=e=>{candidate=e.target.value;show();};cta.href='/design/?part='+partSlug(part)+'&design='+candidate;}
 if(chapter===4){d=await data('C_height');if(t!==ticket)return;viewer.field='height';$('model-caption').textContent=partName(part)+' · teste de altura';$('model-note').textContent='Quatro amostras, mesmas condições. Nenhuma medição física registrada.';cta.href='/test/?part='+partSlug(part);cta.innerHTML='Escolher o teste para imprimir <span>↗</span>';$('chapter-extra').innerHTML='<p class="thermal">A altura também muda o aquecimento. Esse efeito local ainda não foi calibrado.</p>';}
 viewer.setData(d,a,tool);viewer.preset(chapter===2?'top':'iso');viewer.camera.position.multiplyScalar(.82);viewer.controls.update();document.body.classList.remove('loading');if(!matchMedia('(prefers-reduced-motion: reduce)').matches)$('story-viewer').animate([{opacity:.2},{opacity:1}],{duration:500});history.replaceState(null,'','#chapter-'+(chapter+1));
 }catch(e){$('story-error').textContent=e.message;document.body.classList.remove('loading');}}
async function main(){[catalog,legacy]=await Promise.all([json('data/parametric/catalog.json'),json('data/physical/results.json')]);viewer=new LabViewer($('story-viewer'));const initial=Number(location.hash.replace('#chapter-',''))-1;if(initial>=0&&initial<5)chapter=initial;document.querySelectorAll('[data-chapter]').forEach(b=>b.onclick=()=>{chapter=+b.dataset.chapter;show();});$('story-part').onchange=e=>{part=e.target.value;show();};$('previous').onclick=()=>{chapter=Math.max(0,chapter-1);show();};$('next').onclick=()=>{chapter=Math.min(4,chapter+1);show();};document.addEventListener('keydown',e=>{if(['SELECT','INPUT','TEXTAREA'].includes(e.target.tagName))return;if(e.key==='ArrowRight'||e.key==='ArrowLeft'){chapter=Math.max(0,Math.min(4,chapter+(e.key==='ArrowRight'?1:-1)));show();}});await show();}
main().catch(e=>$('story-error').textContent=e.message);
