export const palette={'MATERIAL RESERVE':'#c57b35','DIRECTIONAL COMPLIANCE':'#297c95','BOUNDARY FEED':'#8c69ac','AREA EXPANSION':'#b65269','MIXED':'#75745a','LOW DEMAND':'#b3c7ac'};
export const ranges={demand:[0,40],lambda1:[1,1.6],lambda2:[.8,1.4],J:[.8,2],anisotropy:[1,1.8],xy_feed:[0,15],width:[.8,4],hole_size:[4,7.1],compliance:[1,1.5],delta:[-30,30],error:[-30,30],rank_error:[-20,20],geometry_change:[0,1]};
export function color(value,field){if(value==null||!Number.isFinite(value))return '#d9dcd5';const [a,b]=ranges[field]||ranges.lambda1;const t=Math.max(0,Math.min(1,(value-a)/(b-a)));const stops=['delta','error','rank_error'].includes(field)?[[35,98,152],[245,245,233],[192,49,62]]:[[131,164,129],[232,184,79],[184,44,52]];const j=Math.min(1,Math.floor(t*2)),f=t*2-j;return `rgb(${stops[j].map((v,i)=>Math.round(v+(stops[j+1][i]-v)*f)).join(',')})`;}
export function value(c,geom,field){return field==='direction'?c.lambda1:field==='risk'?c.demand:field==='width'?geom.ligament_width:field==='hole_size'?geom.hole_size:c[field];}
export function mapSVG(data,cells,{field='lambda1',ids=false,arrows=false,scale=1,selected=null,plan=[],overlay=false,changedOnly=false,observed=null,mechanism=null,reference=null,viewBox=null}={}){
  const byId=new Map((observed||[]).map(r=>[r.cell_id,r]));let svg='<svg xmlns="http://www.w3.org/2000/svg" viewBox="-42 -54 84 110" role="group" aria-label="Mapa das células"><defs><marker id="tip" markerWidth="3" markerHeight="3" refX="2.5" refY="1.5" orient="auto-start-reverse"><path d="M0,0 L3,1.5 L0,3" fill="#1f3543"/></marker></defs>';
  if(viewBox)svg=svg.replace('viewBox="-42 -54 84 110"',`viewBox="${viewBox}"`);
  if(!changedOnly)svg+=`<path d="${data.footprint_svg}" fill="#bfc9b6" fill-rule="evenodd"/>`;
  if(changedOnly&&data.geometry_delta){svg+=`<path d="${data.geometry_delta.added_svg}" fill="#267553" fill-rule="evenodd"/><path d="${data.geometry_delta.removed_svg}" fill="#b64052" fill-rule="evenodd"/>`;return svg+'</svg>';}
  if(changedOnly&&reference){const tag=data.id+'-'+data.part;svg+=`<defs><mask id="add-${tag}"><rect x="-50" y="-60" width="100" height="120" fill="white"/><path d="${reference.footprint_svg}" fill="black" fill-rule="evenodd"/></mask><mask id="remove-${tag}"><rect x="-50" y="-60" width="100" height="120" fill="white"/><path d="${data.footprint_svg}" fill="black" fill-rule="evenodd"/></mask></defs><path d="${data.footprint_svg}" fill="#267553" fill-rule="evenodd" mask="url(#add-${tag})"/><path d="${reference.footprint_svg}" fill="#b64052" fill-rule="evenodd" mask="url(#remove-${tag})"/>`;return svg+'</svg>';}
  for(const [i,c] of cells.entries()){const g=data.cells[i],row=byId.get(c.cell_id),p=g.candidate;const changed=Math.abs(g.hole_size-g.original_hole_size)>.008||Math.abs(g.ligament_width-g.original_ligament_width)>.008;
    if(changedOnly&&!changed)continue;let v=value(c,g,field),fill=color(v,field==='direction'?'lambda1':field==='risk'?'demand':field);
    if(field==='risk')fill=c.demand>30?'#b12b40':c.demand>=20?'#e18335':c.demand>=10?'#dac76a':'#8caa82';
    if(field==='mechanism')fill=palette[c.mechanism];if(mechanism&&c.mechanism!==mechanism&&!c.mechanism_flags.includes(mechanism))fill='#e3e5de';
    if(['measured','error','rank_error','failure'].includes(field)){v=field==='failure'?null:row?.[field];fill=field==='failure'?({OK:'#a9c3a1',stretched:'#dbc667',opened:'#dc9b54',cracked:'#ca6170',ruptured:'#9b2343',wrinkled:'#8c73a5',other:'#618597'}[row?.failure_type]||'#ddd'):color(v,field==='measured'?'demand':field);}
    const points=a=>a.map(([x,y])=>`${x},${-y}`).join(' '),[x,y]=c.center;
    svg+=`<polygon data-cell="${i}" tabindex="0" role="button" aria-label="Célula ${c.cell_id}" points="${points(p)}" fill="${overlay?'#edf0e7':fill}" stroke="${selected===i?'#d520ac':plan.includes(c.cell_id)?'#182d25':'#f4f5ef'}" stroke-width="${selected===i?.55:plan.includes(c.cell_id)?.4:.15}"/>`;
    if(overlay)svg+=`<polygon points="${points(g.original)}" fill="none" stroke="#555d55" stroke-width=".18" stroke-dasharray=".6 .4"/><polygon points="${points(p)}" fill="none" stroke="#1c6855" stroke-width=".28"/>`;
    if((arrows||field==='direction')&&c.direction_resolved){const len=Math.min(4,Math.max(.4,Math.abs(c.lambda1-1)*9))*scale,[dx,dy]=c.principal_direction_1.map(v=>v*len/2);svg+=`<path pointer-events="none" d="M${x-dx},${-y+dy} L${x+dx},${-y-dy}" stroke="#1f3543" stroke-width=".18" marker-end="url(#tip)" marker-start="url(#tip)"/>`;}
    if(ids)svg+=`<text pointer-events="none" x="${x}" y="${-y+.6}" text-anchor="middle" font-size="1.75" fill="#101b18">${c.cell_id}</text>`;
  }return svg+'</svg>';
}
export function histogram(cells,field){const values=cells.map(c=>value(c,{},field)).filter(Number.isFinite),[lo,hi]=ranges[field]||ranges.lambda1,bins=Array(12).fill(0);values.forEach(v=>bins[Math.min(11,Math.max(0,Math.floor((v-lo)/(hi-lo)*12)))]++);if(!values.length)return '';const max=Math.max(1,...bins);return `<svg viewBox="0 0 300 100" aria-label="Distribuição">${bins.map((n,i)=>`<rect x="${i*24+6}" y="${80-n/max*65}" width="20" height="${n/max*65}" fill="${color(lo+(hi-lo)*i/11,field)}"/>`).join('')}<text x="5" y="97" font-size="11">${lo}</text><text x="268" y="97" font-size="11">${hi}+</text></svg>`;}
