import {Viewer} from './workbench-viewer.js';
import {mapSVG,color,ranges,palette,histogram} from './physical-maps.js';
import {columns,failures,parseCSV,csv,validateRows,groupKey,measurements,statistics} from './experiment.js';
import {zipSync,strToU8} from 'fflate';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
const fmt=(v,n=2)=>v==null?'—':Number(v).toLocaleString('pt-BR',{maximumFractionDigits:n});
let catalog,plans,part='hab2',design='reserve_high',page='deformation',original,current,selected=0,rows=[],viewers=[],busy=false,animation,revision=0;
const cache=new Map(),S={view:'flat',representation:'stl',step:4,ghost:true,highlight:null,field:'lambda1',sync(source){if(busy)return;busy=true;for(const v of viewers)if(v!==source){v.camera.position.copy(source.camera.position);v.controls.target.copy(source.controls.target);v.controls.update();v.render();}busy=false;},error:message=>status(message),color:v=>S.field==='risk'?(v>30?'#b12b40':v>=20?'#e18335':v>=10?'#dac76a':'#8caa82'):S.field==='mechanism'?palette[v]||'#d9dcd5':color(v,S.field==='direction'?'lambda1':S.field==='risk'?'demand':S.field),value:(e,d)=>{if(['demand','delta','width','compliance','xy_feed'].includes(S.field))return e[S.field];const c=closest(e,d);if(S.field==='mechanism')return c.mechanism;if(S.field==='hole_size')return d.cells[c.id].hole_size;if(S.field==='geometry_change'){const g=d.cells[c.id];return Math.abs(g.hole_size-g.original_hole_size);}return c[S.field==='direction'?'lambda1':S.field==='risk'?'demand':S.field]??c.lambda1;}};
function closest(e,d){const x=(e.flat[0]+e.flat[3])/2,y=(e.flat[1]+e.flat[4])/2;return d.local.reduce((a,b)=>Math.hypot(b.center[0]-x,b.center[1]-y)<Math.hypot(a.center[0]-x,a.center[1]-y)?b:a);}
function status(s,error=false){$('status').textContent=s;$('status').className=error?'error':'';}
async function json(url){if(!cache.has(url)){const r=await fetch(url);if(!r.ok)throw Error(`Arquivo indisponível: ${url}`);cache.set(url,await r.json());}return cache.get(url);}
async function data(id,p){const entry=catalog.designs.find(d=>d.id===id)?.[p];if(!entry)throw Error('Design indisponível para esta peça.');const geom=await json(entry.data),local=(await json(entry.local_data)).map((c,i)=>{const nearest=[...geom.edges].sort((a,b)=>Math.hypot((a.flat[0]+a.flat[3])/2-c.center[0],(a.flat[1]+a.flat[4])/2-c.center[1])-Math.hypot((b.flat[0]+b.flat[3])/2-c.center[0],(b.flat[1]+b.flat[4])/2-c.center[1])).slice(0,6);return {...c,delta:geom.cells[i].candidate_demand-geom.cells[i].baseline_demand,compliance:nearest.reduce((s,e)=>s+e.compliance,0)/nearest.length,geometry_change:Math.abs(geom.cells[i].hole_size-geom.cells[i].original_hole_size)};});return {...geom,local};}
function download(name,content,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
function options(p){return catalog.designs.filter(d=>d[p]).map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('');}
async function refresh(){const rev=++revision;status('Carregando campos…');try{const [a,b]=await Promise.all([data('original',part),data(design,part)]);if(rev!==revision)return;original=a;current=b;viewers[0].setData(a);viewers[1].setData(b);viewers.forEach(v=>v.reset());$('candidate-title').textContent=catalog.designs.find(d=>d.id===design).name;render();status('Modelo geométrico relativo · 65 células com correspondência estável.');}catch(e){status(e.message,true);}}
function render(){if(!current)return;document.querySelector('.viewer-pair').hidden=page==='mechanisms'||page==='design'||(page==='deformation'&&$('view').value==='flat');S.view=$('view').value;S.representation=$('geometry').value==='stl'?'stl':'network';S.field=$('field').value;S.step=Number($('step').value);
  for(const v of viewers){v.update();if($('geometry').value==='tool'){v.lamp.visible=false;v.network.visible=false;v.tool.visible=true;v.tool.material.opacity=.72;v.render();}else v.tool.material.opacity=.12;}
  const bounds=current.geometry_delta?.bounds,viewBox=$('detail').checked&&bounds?[bounds[0]-3,-bounds[3]-3,bounds[2]-bounds[0]+6,bounds[3]-bounds[1]+6].join(' '):null;const opts={viewBox,field:S.field,ids:$('ids').checked,arrows:$('arrows').checked,scale:Number($('scale').value),selected,overlay:$('overlay').checked,changedOnly:$('only').checked,reference:original};
  $('map-left').innerHTML='<figcaption>ORIGINAL</figcaption>'+mapSVG(original,original.local,{...opts,overlay:false,changedOnly:false});$('map-right').innerHTML='<figcaption>'+esc(catalog.designs.find(d=>d.id===design).name)+'</figcaption>'+mapSVG(current,current.local,opts);
  const c=current.local[selected],g=current.cells[selected];$('cell-title').textContent=`Cell ${c.cell_id}`;
  $('cell-detail').innerHTML=`<dl><dt>λ1 / λ2</dt><dd>${fmt(c.lambda1)} / ${fmt(c.lambda2)}</dd><dt>J / anisotropy</dt><dd>${fmt(c.J)} / ${fmt(c.anisotropy)}</dd><dt>d1 · XY</dt><dd>${c.principal_direction_1.map(v=>fmt(v,3)).join(', ')}</dd><dt>Fit RMS</dt><dd>${fmt(c.fit_rms_mm,3)} mm</dd><dt>Fora do plano</dt><dd>${fmt(c.out_of_plane_rms_mm,3)} mm</dd><dt>Hole size</dt><dd>${fmt(g.original_hole_size)} → ${fmt(g.hole_size)} mm</dd><dt>Ligamento</dt><dd>${fmt(g.original_ligament_width)} → ${fmt(g.ligament_width)} mm</dd></dl>${c.fit_warning?'<p class="error">Ajuste afim fraco ou orientação invertida: não interpretar a célula como previsão precisa.</p>':''}<strong>${c.mechanism}</strong><p>${esc(c.mechanism_reason)}</p><small>${c.direction_resolved?'Direção de referência resolvida.':'Direção quase isotrópica: seta omitida.'} ${c.boundary_sensitivity_available?'Sensibilidade periférica calculada.':'Sensibilidade periférica não calculada neste candidato; BOUNDARY FEED não é atribuído.'}</small>`;
  $('histogram').innerHTML=histogram(current.local,S.field);$('mechanism-legend').innerHTML=Object.entries(palette).map(([k,v])=>`<p><i class="swatch" style="background:${v}"></i>${k} · ${current.local.filter(c=>c.mechanism===k).length}</p>`).join('');
  const range=ranges[S.field]||ranges.lambda1;$('legend').textContent=$('only').checked?'Verde: material adicionado · vermelho: removido':S.field==='mechanism'?'Categorias heurísticas':S.field==='risk'?'Demanda: <10% · 10–20% · 20–30% · >30%':`${S.field}: ${range[0]} → ${range[1]} · valores externos saturam`;
  $('field-note').textContent=$('only').checked?'Diferença geométrica exata da pegada: verde = material adicionado; vermelho = removido. Núcleo e aro sem alteração ficam ocultos.':S.field==='mechanism'?'Mechanism classification is a design heuristic derived from geometric behavior.':S.field==='geometry_change'?'Geometry delta: proxy local |Δ abertura equivalente| em mm. Overlay mostra contornos reais.':S.field==='compliance'?'3D: razão caminho/corda do ligamento; mapa celular usa a média dos caminhos vizinhos.':'F: ajuste afim XY → plano tangente de seis nós por célula. Setas ±d1 em coordenadas planas; comprimento proporcional a |λ1−1|. A vista Formed mostra uma rede, não um sólido deformado.';
  $('metrics').innerHTML=[['P95','p95'],['P99','p99'],['Máximo','maximum'],['Críticos >30%','critical_edges'],['Área aberta','open_area'],['Largura mínima','minimum_ligament_width']].map(([title,k])=>`<div><small>${title} · Original → Candidate</small><strong>${fmt(original.metrics[k],1)} → ${fmt(current.metrics[k],1)}</strong></div>`).join('');
  const entry=catalog.designs.find(d=>d.id===design);$('design-explanation').textContent=entry[part].why||`${entry.name}. Pitch e posições dos nós do núcleo preservados. ${entry.parameters?.changed_paths?.length||0} caminhos modificados. Solver: ${entry[part].solver.success?'convergiu':'NÃO convergiu — resultado exploratório'}. Não representa validação física.`;
}
function navigate(target){page=target;document.querySelectorAll('[data-page]').forEach(b=>b.setAttribute('aria-current',String(b.dataset.page===page)));for(const id of ['experiment','calibration','print'])$(id).hidden=id!==page;$('engineering').hidden=['experiment','calibration','print'].includes(page);if(page==='mechanisms')$('field').value='mechanism';if(page==='deformation')$('field').value='lambda1';if(page==='design'){$('overlay').checked=true;$('field').value='geometry_change';}else $('overlay').checked=false;if(page==='compare')$('field').value='delta';if(page==='geometry')$('geometry').value='stl';render();history.replaceState(null,'',`?page=${page}`);}
function metricCards(m){return [['Spearman',fmt(m.spearman,3)],[`Top-${m.k} hit · ${m.n}/65 medidas`,m.hit==null?'—':fmt(m.hit*100,1)+'%'],['Hotspot precision',m.precision==null?'—':fmt(m.precision*100,1)+'%'],['Hotspot recall',m.recall==null?'—':fmt(m.recall*100,1)+'%']].map(([l,v])=>`<div><small>${l}</small><strong>${v}</strong></div>`).join('');}
function sampleOptions(){const groups=[...new Set(rows.filter(r=>r.sample_id&&r.experiment_id).map(groupKey))];for(const id of ['sample','calibration-sample','validation-sample'])$(id).innerHTML='<option value="">Selecionar amostra</option>'+groups.map(g=>`<option>${esc(g)}</option>`).join('');if(groups.length)$('sample').value=groups[0];}
async function showExperiment(){try{const subset=rows.filter(r=>groupKey(r)===$('sample').value);if(!subset.length){$('experiment-status').textContent='NO PHYSICAL VALIDATION DATA YET';for(const id of ['thermal','exp-metrics','predicted-map','measured-map','measured-table'])$(id).replaceChildren();return;}const first=subset[0],d=await data(first.design,first.part),measured=measurements(subset,d.local),stats=statistics(measured);$('experiment-status').textContent=`${stats.n} células medidas · ${stats.labeled} classificações de falha. Ranking apenas nas células medidas; K=min(10, floor(n/3)). Empates usam posições médias e participação fracionária. Precisão/recall usam demanda de ligamento >30% contra failure explícito.`;$('exp-metrics').innerHTML=metricCards(stats);
  $('predicted-map').innerHTML=mapSVG(d,d.local.map(c=>({...c,demand:100*(c.lambda1-1)})),{field:'demand',ids:true});$('measured-map').innerHTML=mapSVG(d,d.local,{field:$('observed-field').value,ids:true,observed:measured});$('observed-label').textContent=$('observed-field').selectedOptions[0].textContent+' · ausente = cinza';
  $('thermal').textContent='THERMOFORMING CONDITION · '+['material','heating_device','heating_distance_mm','heating_time_s','surface_temperature_c','forming_time_s','hold_time_s'].map(k=>k+': '+(first[k]||'não informado')).join(' · ');
  $('measured-table').innerHTML='<tr><th>Cell</th><th>λ1 previsto / medido</th><th>λ2 previsto / medido</th><th>J previsto / medido</th><th>Erro λ1 · p.p.</th><th>Rank error</th><th>Ocorrência</th></tr>'+measured.map(r=>`<tr><td>${r.cell_id}</td><td>${fmt(r.c.lambda1)} / ${fmt(r.lambda1_measured)}</td><td>${fmt(r.c.lambda2)} / ${fmt(r.lambda2_measured)}</td><td>${fmt(r.c.J)} / ${fmt(r.J_measured)}</td><td>${fmt(r.error)}</td><td>${fmt(r.rank_error)}</td><td>${esc(r.failure_type)}</td></tr>`).join('');
}catch(e){$('experiment-status').textContent=e.message;}}
async function importMeasurements(file){const text=await file.text(),parsed=file.name.endsWith('.json')?JSON.parse(text):parseCSV(text);rows=validateRows(parsed.measurements||parsed,catalog);sampleOptions();await showExperiment();}
function makeManual(){const labels={L1_before_mm:'L1 antes · mm',L1_after_mm:'L1 depois · mm',L2_before_mm:'L2 antes · mm',L2_after_mm:'L2 depois · mm'};$('manual-fields').innerHTML=columns.map(k=>{let input=k==='part'?'<select name="part"><option>submerged</option><option>hab2</option></select>':k==='design'?`<select name="design">${catalog.designs.map(d=>`<option value="${d.id}">${esc(d.name)}</option>`).join('')}</select>`:k==='failure_type'?`<select name="failure_type"><option value=""></option>${failures.map(v=>`<option>${v}</option>`).join('')}</select>`:k==='failure'?'<select name="failure"><option value=""></option><option>true</option><option>false</option></select>':`<input name="${k}" ${['experiment_id','sample_id','cell_id'].includes(k)?'required':''} ${k==='date'?'type="date"':''}>`;return `<label>${labels[k]||k}${input}</label>`;}).join('');}
async function combinedZIP(){const files={},configuration={status:'UNVALIDATED TEST CONFIGURATION',choices:{}};for(const p of ['hab2','submerged']){const id=$('lamp-'+p).value,d=catalog.designs.find(d=>d.id===id),r=await fetch(d[p].stl);if(!r.ok)throw Error('STL indisponível');files[`${p}_${id}.stl`]=new Uint8Array(await r.arrayBuffer());configuration.choices[p]={design:id,metrics:d[p].metrics,validation:d[p].validation};}files['configuration.json']=strToU8(JSON.stringify(configuration,null,2));files['README.txt']=strToU8('Independent part choices. No physical validation yet. Inspect slicer layers. Original as supplied may contain mesh defects.');download('LAMPFORM_CONFIGURATION.zip',zipSync(files),'application/zip');$('lamp-status').textContent='Pacote combinado gerado com os dois STL selecionados.';}
async function sha(value){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(value))))].map(v=>v.toString(16).padStart(2,'0')).join('');}
async function calibrationJob(){const a=rows.filter(r=>groupKey(r)===$('calibration-sample').value),b=rows.filter(r=>groupKey(r)===$('validation-sample').value);if(a.filter(r=>r.L1_before_mm!=='').length<5||b.filter(r=>r.L1_before_mm!=='').length<5||a.some(r=>!['original','test_a'].includes(r.design))||b.some(r=>['original','test_a'].includes(r.design))||a[0]?.sample_id===b[0]?.sample_id||a[0]?.part!==b[0]?.part)throw Error('Escolha amostras distintas: Original para calibração e Candidate para validação, da mesma peça, com pelo menos cinco células medidas em cada.');const job={schema:'lampform-calibration-v1',calibration:a,validation:b};job.dataset_digest=await sha({calibration:a,validation:b});download('calibration_job.json',JSON.stringify(job,null,2));$('calibration-status').textContent='Trabalho exportado. O modelo continua UNCALIBRATED até executar o ajuste e importar o relatório.';}
async function sensors(file){const records=parseCSV(await file.text());if(!records.length)throw Error('CSV de sensores vazio.');const fields=['time_s','displacement_mm','force_n','temperature_c'];for(const r of records)for(const k of fields)if(r[k]!==''&&!Number.isFinite(Number(r[k])))throw Error('Sensor contém valor inválido.');if(records.some(r=>r.time_s===''))throw Error('time_s obrigatório.');const panels=[['time_s','temperature_c'],['displacement_mm','force_n']].map(([xk,yk])=>{const r=records.filter(r=>r[xk]!==''&&r[yk]!==''&&r[xk]!=null&&r[yk]!=null);if(r.length<2)return `<p>Sem pares ${xk} / ${yk} suficientes.</p>`;const xs=r.map(r=>+r[xk]),ys=r.map(r=>+r[yk]),lo=Math.min(...xs),hi=Math.max(...xs),a=Math.min(...ys),b=Math.max(...ys),points=r.map(v=>`${40+(v[xk]-lo)/(hi-lo||1)*430},${220-(v[yk]-a)/(b-a||1)*180}`).join(' ');return `<figure><figcaption>${xk} (${fmt(lo)}–${fmt(hi)}) × ${yk} (${fmt(a)}–${fmt(b)})</figcaption><svg viewBox="0 0 500 250"><polyline points="${points}" fill="none" stroke="#346453" stroke-width="2"/></svg></figure>`;});$('sensor-chart').innerHTML=panels.join('');}
async function main(){try{if(new URLSearchParams(location.search).get('mode')==='story'||new URLSearchParams(location.search).get('mode')==='capture'){location.replace('story.html'+location.search);return;}
  [catalog,plans]=await Promise.all([json('data/physical/results.json'),json('data/physical/measurement_plan.json')]);design=catalog.independent_choices.hab2;$('design').innerHTML=options(part);$('design').value=design;
  for(const p of ['hab2','submerged']){$('lamp-'+p).innerHTML=options(p);$('lamp-'+p).value=catalog.independent_choices[p];}
  $('test-matrix').innerHTML='<table><tr><th>Teste · Sub-Merged</th><th>Core</th><th>Boundary</th><th>STL validation</th><th>Download</th></tr>'+catalog.causal_tests.map(id=>{const d=catalog.designs.find(d=>d.id===id),r=d.submerged;return `<tr><td>${esc(d.name)}</td><td>${['test_b','test_d'].includes(id)?'Reserve':'Original'}</td><td>${['test_c','test_d'].includes(id)?'2 conectores curvos':'Original'}</td><td>${r.validation.printable_geometry_checks_passed?'PASS':'FAIL'} · solver ${r.solver.success?'convergiu':'não convergiu'}</td><td><a href="${r.stl}" download>STL ↓</a></td></tr>`;}).join('')+'</table><p>A é reparado para remover o defeito topológico como variável. C mantém pitch, furos e material do núcleo. Não se atribui auxeticidade ao conceito bidirecional sem medição.</p>';
  viewers=[new Viewer($('view-left'),S),new Viewer($('view-right'),S)];makeManual();
  document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigate(b.dataset.page));$('part').onchange=()=>{part=$('part').value;design=catalog.independent_choices[part];$('design').innerHTML=options(part);$('design').value=design;refresh();};$('design').onchange=()=>{design=$('design').value;refresh();};
  for(const id of ['field','view','geometry','step','ids','arrows','scale','overlay','only','detail'])$(id).onchange=render;
  $('reset').onclick=()=>viewers.forEach(v=>v.reset());$('play').onclick=()=>{if(animation){clearInterval(animation);animation=null;$('play').textContent='Reproduzir etapas';return;}$('view').value='formed';$('geometry').value='network';$('play').textContent='Pausar';animation=setInterval(()=>{$('step').value=(Number($('step').value)+1)%5;render();},1100);};
  for(const id of ['map-left','map-right']){const inspect=e=>{const target=e.target.closest('[data-cell]');if(target){selected=+target.dataset.cell;render();}};$(id).onclick=inspect;$(id).onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();inspect(e);}};}
  $('import').onchange=async()=>{try{await importMeasurements($('import').files[0]);}catch(e){$('experiment-status').textContent=e.message;}};$('sample').onchange=showExperiment;$('observed-field').onchange=showExperiment;
  $('export-csv').onclick=()=>download('measurements.csv',csv(rows),'text/csv');$('export-json').onclick=()=>download('measurements.json',JSON.stringify({schema:'lampform-experiment-v1',measurements:rows},null,2));
  $('manual').onsubmit=e=>{e.preventDefault();try{rows=validateRows([...rows,Object.fromEntries(new FormData(e.target))],catalog);sampleOptions();showExperiment();}catch(e){$('experiment-status').textContent=e.message;}};
  $('lamp-zip').onclick=()=>combinedZIP().catch(e=>$('lamp-status').textContent=e.message);$('sensors').onchange=()=>sensors($('sensors').files[0]).catch(e=>$('sensor-chart').textContent=e.message);
  $('calibration-job').onclick=()=>calibrationJob().catch(e=>$('calibration-status').textContent=e.message);
  $('calibration-result').onchange=async()=>{try{const r=JSON.parse(await $('calibration-result').files[0].text());if(r.schema!=='lampform-calibration-result-v1'||!r.calibrated_on||!r.validation_sample||r.calibrated_on===r.validation_sample||!r.dataset_digest)throw Error('Relatório de calibração inválido.');const ca=rows.filter(x=>groupKey(x)===$('calibration-sample').value),va=rows.filter(x=>groupKey(x)===$('validation-sample').value);if(!ca.length||!va.length||await sha({calibration:ca,validation:va})!==r.dataset_digest)throw Error('Selecione os mesmos datasets usados no ajuste. O hash do relatório precisa corresponder às medidas carregadas.');if(!r.calibration_fit?.solver_converged||r.calibration_fit.n<5)throw Error('Ajuste sem convergência ou sem medidas suficientes.');$('calibration-status').textContent='CALIBRATED ON: '+r.calibrated_on+' · relatório offline importado; não altera as previsões base da bancada.';$('calibration-report').innerHTML=`<h3>Calibration fit</h3><pre>${esc(JSON.stringify(r.calibration_fit,null,2))}</pre><h3>Blind validation performance</h3><pre>${esc(JSON.stringify(r.validation_performance,null,2))}</pre><p>Parâmetros: ${esc(JSON.stringify(r.parameters))}</p>`;}catch(e){$('calibration-status').textContent=e.message;}};
  await refresh();navigate(new URLSearchParams(location.search).get('page')||'deformation');
}catch(e){status(e.message,true);console.error(e);}}
await main();
