import {Viewer} from './workbench-viewer.js';
import * as THREE from 'three';
import {mapSVG,color,palette} from './physical-maps.js';
const $=id=>document.getElementById(id),query=new URLSearchParams(location.search);let scenes,catalog,scene=Math.min(12,Math.max(1,Number(query.get('scene'))||1)),phase=0,views=[],a,b,token=0,syncing=false;
const cache=new Map();async function json(url){if(!cache.has(url)){const r=await fetch(url);if(!r.ok)throw Error(url+' indisponível');cache.set(url,await r.json());}return cache.get(url);}
async function data(id,p='submerged'){const r=catalog.designs.find(d=>d.id===id)[p];return {...await json(r.data),local:await json(r.local_data)};}
const S={view:'flat',representation:'stl',step:4,ghost:true,highlight:null,color:v=>color(v,'demand'),value:e=>e.demand,error:m=>$('story-error').textContent=m,sync(source){if(syncing)return;syncing=true;views.forEach(v=>{if(v!==source){v.camera.position.copy(source.camera.position);v.controls.target.copy(source.controls.target);v.controls.update();v.render();}});syncing=false;}};
function map(data,field,extra={}){return mapSVG(data,data.local,{field,arrows:field==='lambda1'||field==='direction',reference:a,...extra});}
function camera(){for(const v of views){v.camera.position.fromArray(scenes[scene-1].camera.position);v.controls.target.fromArray(scenes[scene-1].camera.target);v.controls.update();v.render();}}
async function show(){const ticket=++token;$('stage').dataset.ready='false';try{const s=scenes[scene-1];[a,b]=await Promise.all([data('original'),data(s.candidate)]);if(ticket!==token)return;
  S.view='flat';S.representation='stl';S.step=4;S.ghost=true;$('story-callout').textContent='';$('story-note').textContent='Geometric model · NO PHYSICAL VALIDATION DATA YET';
  $('progress').textContent=`${String(scene).padStart(2,'0')} / 12`;$('scene-label').textContent=`SCENE ${String(scene).padStart(2,'0')} · ${s.phases[phase]}`;$('scene-title').textContent=s.title;$('scene-message').textContent=s.message;
  $('phases').innerHTML=s.phases.map((name,i)=>`<button data-phase="${i}" aria-pressed="${i===phase}">${name}</button>`).join('');
  $('story-viewers').hidden=false;$('story-maps').hidden=true;$('story-diagram').hidden=true;
  if([1,2,4,5,8].includes(scene))b=a;const single=[1,2,4,5,8].includes(scene);$('story-viewers').classList.toggle('single',single);$('story-right').hidden=single;
  if(scene===1&&phase===1)S.ghost=true;
  if(scene===2&&phase>0)S.view='formed';if(scene===2&&phase===2)S.highlight=a.edges.reduce((x,y)=>x.demand>y.demand?x:y).parent;
  else S.highlight=null;
  if(scene===5){S.view='formed';S.step=phase;}
  views[0].setData(a);views[1].setData(b);
  if(scene===3){views[0].setData(await data('original','hab2'));views[1].setData(a);for(const v of views){v.lamp.visible=false;v.network.visible=false;v.tool.visible=true;v.tool.material.opacity=.8;}const dims=d=>{const p=d.tool.positions;return [0,1,2].map(k=>{let lo=Infinity,hi=-Infinity;for(let i=k;i<p.length;i+=3){lo=Math.min(lo,p[i]);hi=Math.max(hi,p[i]);}return (hi-lo).toFixed(1);}).join(' × ');};$('story-callout').textContent='Mold: '+dims(views[0].data)+' mm · Push: '+dims(a)+' mm';$('story-note').textContent='Ferramentas reais em vistas separadas; contato e fechamento não resolvidos.';}
  if(scene===1){views[0].tool.visible=phase===1;views[0].tool.material.opacity=.15;}
  if(scene===4&&phase===2){for(const v of views){v.lamp.visible=false;v.network.visible=false;const positions=new Map();v.data.edges.forEach(e=>[e.flat.slice(0,3),e.flat.slice(3)].forEach(p=>positions.set(p.join(','),p)));const g=new THREE.BufferGeometry().setFromPoints([...positions.values()].map(p=>new THREE.Vector3(...p))),points=new THREE.Points(g,new THREE.PointsMaterial({color:'#325f4b',size:2}));v.scene.add(points);v.objects.push(points);}}
  if(scene===4&&phase===3){S.representation='network';views.forEach(v=>v.update());}
  const showMaps=(left,right)=>{$('story-viewers').hidden=true;$('story-maps').hidden=false;$('story-maps').innerHTML=left+right;};
  if(scene===4&&phase===1)showMaps(map(a,'lambda1',{ids:true}),map(a,'lambda1',{ids:true}));
  if(scene===6){$('story-note').textContent=phase===1?'λ2: 0.8 → 1.4 · extremes saturated · geometric proxy':'λ1: 1.0 → 1.6 · extremes saturated · arrows ±d1, length ∝ |λ1−1|';const f=['lambda1','lambda2','direction'][phase];showMaps(map(a,f),map(b,f));$('story-callout').textContent=`${f} · Original | Reserve Search 3 · mesma escala`;}
  if(scene===7){const m=s.phases[phase];showMaps(map(a,'mechanism',{mechanism:m}),map(b,'mechanism',{mechanism:m}));$('story-callout').textContent=`${m}: ${a.local.filter(c=>c.mechanism===m||c.mechanism_flags.includes(m)).length} células Original. Hipótese de projeto.`;}
  if(scene===8){if(phase===1)showMaps(map(a,'demand'),map(a,'risk'));$('story-callout').textContent=`P95 ${a.metrics.p95.toFixed(1)}% · Max ${a.metrics.maximum.toFixed(1)}% · ${a.metrics.critical_edges} ligamentos críticos`;} 
  if(scene===9){if(phase===3)b=await data('test_c');const bounds=phase===3?b.geometry_delta?.bounds:null,viewBox=bounds?[bounds[0]-3,-bounds[3]-3,bounds[2]-bounds[0]+6,bounds[3]-bounds[1]+6].join(' '):null;showMaps(map(a,'hole_size',{viewBox}),map(b,phase===1?'width':'direction',{viewBox,overlay:phase!==1,changedOnly:phase===0||phase===3}));$('story-callout').textContent=phase===3?'Core preservado · dois conectores modificados · verde: adicionado, vermelho: removido':phase===2?'Caminhos S selecionados por alinhamento com d1. Não é melhora comprovada.':'Original tracejado · candidato sólido';}
  if(scene===10&&phase===1){const delta=b.local.map((c,i)=>({...c,delta:c.demand-a.local[i].demand}));showMaps(map(a,'demand'),mapSVG(b,delta,{field:'delta'}));$('story-callout').textContent='Azul: melhora · branco: similar · vermelho: piora · ±30 p.p.';}
  if(scene===11){$('story-viewers').hidden=true;$('story-diagram').hidden=false;$('story-diagram').innerHTML='<p>Prediction<br>↓<br>Print → Thermoform<br>↓<br>Measure</p>';}
  if(scene===12){const d=await data(['test_a','test_b','test_c','test_d','test_a'][phase]);showMaps(map(d,'demand',{ids:true}),phase===4?'<svg viewBox="0 0 600 400"><text x="300" y="180" text-anchor="middle" font-size="20" fill="#52684f">NO PHYSICAL VALIDATION</text><text x="300" y="215" text-anchor="middle" font-size="20" fill="#52684f">DATA YET</text></svg>':map(d,'direction'));$('story-callout').textContent='A/B/C/D · mesmo núcleo nominal e fatores controlados. Imprimir para aprender.';}
  camera();const params=new URLSearchParams({scene:String(scene).padStart(2,'0')});if(query.get('mode')==='capture')params.set('mode','capture');history.replaceState(null,'','story.html?'+params);$('stage').dataset.ready='true';
}catch(e){$('story-error').textContent=e.message;console.error(e);}}
async function capture(){const canvas=document.createElement('canvas');canvas.width=1920;canvas.height=1080;const ctx=canvas.getContext('2d');ctx.fillStyle='#f4f5ef';ctx.fillRect(0,0,1920,1080);ctx.fillStyle='#263129';ctx.font='24px Arial';ctx.fillText('LAMPFORM LAB',80,60);ctx.font='54px Arial';ctx.fillText(scenes[scene-1].title,80,145);const svg=$('story-maps').querySelectorAll('svg');if(!$('story-maps').hidden){let i=0;for(const el of svg){const img=new Image(),url=URL.createObjectURL(new Blob([el.outerHTML],{type:'image/svg+xml'}));img.src=url;await img.decode();ctx.drawImage(img,170+i*850,205,700,680);URL.revokeObjectURL(url);i++;}}else if(!$('story-viewers').hidden){const active=views.filter(v=>!v.element.hidden);active.forEach((v,i)=>{v.render();const source=v.renderer.domElement,box=active.length===1?1760:870,factor=Math.min(box/source.width,620/source.height),w=source.width*factor,h=source.height*factor;ctx.drawImage(source,80+i*900+(box-w)/2,220+(620-h)/2,w,h);});}else{ctx.font='52px Arial';ctx.fillText('Prediction → Print → Thermoform → Measure',170,530);}ctx.font='24px Arial';const message=scenes[scene-1].message;const words=message.split(' ');let line='',y=960;for(const word of words){if(ctx.measureText(line+word).width>1750){ctx.fillText(line,80,y);line='';y+=34;}line+=word+' ';}ctx.fillText(line,80,y);ctx.font='18px Arial';ctx.fillText('Geometric model · NO PHYSICAL VALIDATION DATA YET',80,1040);canvas.toBlob(blob=>{const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=scenes[scene-1].frame;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);});}
scenes=await json('data/storyboard.json');catalog=await json('data/physical/results.json');if(query.get('mode')==='capture')document.body.classList.add('capture');views=[new Viewer($('story-left'),S),new Viewer($('story-right'),S)];views.forEach(v=>v.renderer.setClearColor('#f4f5ef'));
function next(delta){scene=Math.max(1,Math.min(12,scene+delta));phase=0;show();}$('next').onclick=()=>next(1);$('previous').onclick=()=>next(-1);$('phases').onclick=e=>{if(e.target.dataset.phase!==undefined){phase=+e.target.dataset.phase;show();}};$('capture').onclick=()=>capture().catch(e=>$('story-error').textContent=e.message);document.addEventListener('keydown',e=>{if(e.key==='Escape'){location.href='index.html';return;}if(['ArrowRight','ArrowLeft',' '].includes(e.key)){e.preventDefault();next(e.key==='ArrowLeft'?-1:1);}});await show();
